//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsKazalarıProje.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrashUsers
    {
        public int Id { get; set; }
        public string NameSurname { get; set; }
        public Nullable<int> Age { get; set; }
        public string Weight { get; set; }
        public string Height { get; set; }
        public string Class { get; set; }
        public string CrashWhy { get; set; }
        public string CrashPlace { get; set; }
        public string CrashAbout { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
